# PhantomScan Policy Configuration
# Adjust these values to tune scoring behavior and operational parameters

# Scoring Weights (must sum to 1.0)
weights:
  name_suspicion: 0.30
  newness: 0.25
  repo_missing: 0.15
  maintainer_reputation: 0.15
  script_risk: 0.10
  version_flip: 0.03
  readme_plagiarism: 0.02

# Heuristic Parameters
heuristics:
  # Days since creation to consider "new" (1.0 score at 0 days, 0.0 at this threshold)
  new_package_days: 30

  # Brand/API names that trigger suspicion when used as prefixes
  suspicious_prefixes:
    - openai
    - huggingface
    - microsoft
    - azure
    - copilot
    - langchain
    - anthropic
    - cohere
    - replicate
    - stability
    - midjourney

  # Suffix patterns that often indicate slopsquatting
  suspicious_suffixes:
    - "-cli"
    - "-tools"
    - "-utils"
    - "-sdk"
    - "-x"
    - "2"
    - "-py"
    - "-python"
    - "-js"
    - "-node"

  # Canonical packages to check for close similarity (fuzzy matching)
  canonical_packages:
    pypi:
      - requests
      - numpy
      - pandas
      - torch
      - tensorflow
      - scikit-learn
      - matplotlib
      - pillow
      - flask
      - django
      - fastapi
      - pytest
      - black
      - ruff
    npm:
      - react
      - vue
      - angular
      - express
      - lodash
      - webpack
      - axios
      - moment
      - typescript
      - next
      - eslint
      - prettier

  # Fuzzy match threshold (0-100, lower is more similar)
  fuzzy_threshold: 15

  # Thresholds for new heuristics
  thresholds:
    readme_plagiarism: 0.85  # Similarity threshold for flagging plagiarism
    version_flip_window_days: 30  # Time window for version comparison (days)
    maintainer_age_days: 14  # Days to consider maintainer account "young"

  # Disposable email domains (red flags for maintainer quality)
  disposable_email_domains:
    - mailinator
    - 10minutemail
    - yopmail
    - sharklasers
    - guerrillamail
    - temp-mail
    - throwaway

  # Enrichment lookups (requires external API keys)
  lookups:
    enable_dependents: false  # Require LIBRARIES_IO_KEY env var
    libraries_io_api: "https://libraries.io/api"
    dependents_low_threshold: 0  # Flag packages with 0 dependents
    dependents_high_threshold: 50  # Consider >= 50 as established
    timeout: 5  # Timeout for enrichment calls (seconds)

# Feed Generation
feed:
  # Number of top candidates to include in daily feed
  top_n: 50
  # Minimum score to include (0.0 - 1.0)
  min_score: 0.3

# Data Sources
sources:
  pypi:
    enabled: true
    # RSS feeds
    rss_packages: "https://pypi.org/rss/packages.xml"
    rss_updates: "https://pypi.org/rss/updates.xml"
    # JSON API template
    json_api: "https://pypi.org/pypi/{name}/json"
    # Request timeout (seconds)
    timeout: 10
    # Retry attempts
    retries: 3

  npm:
    enabled: true
    # Changes feed
    changes_feed: "https://replicate.npmjs.com/_changes"
    # Fetch limit per run
    limit: 1000
    timeout: 10
    retries: 3

# Network Configuration
network:
  # User-Agent for API requests
  user_agent: "PhantomScan/0.1.0 (security research; +https://github.com/example/phantom-dependency-radar)"
  # Connection pool size
  pool_size: 10
  # API endpoint timeout (seconds) - prevents long-running enrichment fan-outs
  api_timeout_seconds: 8

# Storage
storage:
  # DuckDB database file
  duckdb_path: "data/radar.duckdb"
  # Retain history for N days (0 = indefinite)
  retention_days: 90
